spring:
  application:
    name: SpringSecurityDemo


  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    username: postgres
    password: root

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

#  security:
#    user:
#      name: sairam
#      password: 12345


server:
  servlet:
    context-path: /api/v1


jwt:
  secret: Tp2ZXcxJYA9nxNBgPXBtejP2kVB3HQjzKZ0M10TnDhIT64e2kf6xrgO9Tgl